### ISSUE TITLE
无法运行app.py

### ISSUE THREAD

**Issue by taIes** [lyxhh/lxhToolHTTPDecrypt#16]
你好，mac和ios的frida相同版本，frida-ps-U正常，运行python3 app.py 出现以下报错，找了好久没找到问题所在
```
➜  HTTPDecrypt python3 app.py
[15:57:50] [INFO] HTTP Decrypt running at http://127.0.0.1:8088
 * Serving Flask app "globalenv" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "app.py", line 115, in <module>
    main()
  File "app.py", line 111, in main
    socketio.run(app, host=host, port=FlaskPort, debug=True)
  File "/usr/local/lib/python3.7/site-packages/flask_socketio/__init__.py", line 541, in run
    use_reloader=use_reloader, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 1007, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "/usr/local/lib/python3.7/site-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/tale/Downloads/lxhToolHTTPDecrypt-master/HTTPDecrypt/app.py'
```

**Comment by lyxhh** [comment]
创建个python的虚拟环境，在虚拟环境里面运行试试，

**Comment by taIes** [comment]
谢谢哈，已解决~
