### ISSUE TITLE
在toburp中hook,程序出现报错

### ISSUE THREAD

**Issue by m0n3t4r** [lyxhh/lxhToolHTTPDecrypt#29]
![image](https://user-images.githubusercontent.com/74404420/105313101-caf4f400-5bf8-11eb-95f4-b60c7e8b3a26.png)
大佬,请问这种情况引起的原因是什么,有什么解决方案吗?
python:3.8.7
frida:14.6.2
图片加载不出的话下面复制了报错信息
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\frida\core.py", line 383, in _on_message
    callback(message, data)
  File "E:\android_test\lxhToolHTTPDecrypt-master\lxhToolHTTPDecrypt-master\HTTPDecrypt\util.py", line 147, in on_message
    {'data': cgi.escape(json.dumps(j_info))},
AttributeError: module 'cgi' has no attribute 'escape'

**Comment by lyxhh** [comment]
python版本太高了 那个库得方法过气了
