### ISSUE TITLE
运行遇到一点问题

### ISSUE THREAD

**Issue by Blueskysun** [lyxhh/lxhToolHTTPDecrypt#5]
Exception in thread Thread-24:
Traceback (most recent call last):
  File "G:\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "G:\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "G:\Python36\lib\site-packages\socketio\server.py", line 599, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "G:\Python36\lib\site-packages\socketio\server.py", line 628, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "G:\Python36\lib\site-packages\flask_socketio\__init__.py", line 277, in _handler
    *args)
  File "G:\Python36\lib\site-packages\flask_socketio\__init__.py", line 680, in _handle_event
    ret = handler(*args)
  File "C:\Users\nsfocus-pc\Desktop\lxhToolHTTPDecrypt-master\HTTPDecrypt\socketutil.py", line 235, in doLoadHook
    script_content = render('./script/hooks.js', content)
  File "C:\Users\nsfocus-pc\Desktop\lxhToolHTTPDecrypt-master\HTTPDecrypt\socketutil.py", line 108, in render
    ).get_template(filename).render(context)
  File "G:\Python36\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "G:\Python36\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "G:\Python36\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "G:\Python36\lib\site-packages\jinja2\loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: hooks.js

除了安卓系统版本，其他应该都是按照说明配的，望解答一下

**Comment by Blueskysun** [comment]
hook 和 find 均报这种错误

**Comment by lyxhh** [comment]
看报错说的是找不到 HTTPDecrypt/script/hooks.js，请检查hooks.js是否存在。
