### ISSUE TITLE
hook时控制台报错。

### ISSUE THREAD

**Issue by SRW-OG** [lyxhh/lxhToolHTTPDecrypt#6]
```
[17:38:59] [INFO] unload_findclass_script
message handler error
Traceback (most recent call last):
  File "D:\DevLab\py3_env\.venv\lib\site-packages\engineio\server.py", line 505, in _trigger_event
    return self.handlers[event](*args)
  File "D:\DevLab\py3_env\.venv\lib\site-packages\socketio\server.py", line 590, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "D:\DevLab\py3_env\.venv\lib\site-packages\socketio\server.py", line 526, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "D:\DevLab\py3_env\.venv\lib\site-packages\socketio\server.py", line 529, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "D:\DevLab\py3_env\.venv\lib\site-packages\socketio\server.py", line 558, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "D:\DevLab\py3_env\.venv\lib\site-packages\flask_socketio\__init__.py", line 259, in _handler
    *args)
  File "D:\DevLab\py3_env\.venv\lib\site-packages\flask_socketio\__init__.py", line 660, in _handle_event
    ret = handler(*args)
  File "D:\PenLAB\burpsuite_pro\lxhToolHTTPDecrypt\HTTPDecrypt\socketutil.py", line 31, in unloadfindclassScript
    genv.script.unload()
AttributeError: 'NoneType' object has no attribute 'unload'
```

start页面能看到手机上的包名，选择包，`confirm`，Hooks看不到任何内容，控制台报错。

android 9 ，已root

**Comment by difa12321** [comment]
> ```
> [17:38:59] [INFO] unload_findclass_script
> message handler error
> Traceback (most recent call last):
>   File "D:\DevLab\py3_env\.venv\lib\site-packages\engineio\server.py", line 505, in _trigger_event
>     return self.handlers[event](*args)
>   File "D:\DevLab\py3_env\.venv\lib\site-packages\socketio\server.py", line 590, in _handle_eio_message
>     self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
>   File "D:\DevLab\py3_env\.venv\lib\site-packages\socketio\server.py", line 526, in _handle_event
>     self._handle_event_internal(self, sid, data, namespace, id)
>   File "D:\DevLab\py3_env\.venv\lib\site-packages\socketio\server.py", line 529, in _handle_event_internal
>     r = server._trigger_event(data[0], namespace, sid, *data[1:])
>   File "D:\DevLab\py3_env\.venv\lib\site-packages\socketio\server.py", line 558, in _trigger_event
>     return self.handlers[namespace][event](*args)
>   File "D:\DevLab\py3_env\.venv\lib\site-packages\flask_socketio\__init__.py", line 259, in _handler
>     *args)
>   File "D:\DevLab\py3_env\.venv\lib\site-packages\flask_socketio\__init__.py", line 660, in _handle_event
>     ret = handler(*args)
>   File "D:\PenLAB\burpsuite_pro\lxhToolHTTPDecrypt\HTTPDecrypt\socketutil.py", line 31, in unloadfindclassScript
>     genv.script.unload()
> AttributeError: 'NoneType' object has no attribute 'unload'
> ```
> 
> start页面能看到手机上的包名，选择包，`confirm`，Hooks看不到任何内容，控制台报错。
> 
> android 9 ，已root

先在finds点confirm，查找关键性的包名，再在hooks里查看。直接hooks，app会崩溃退出，控制台也容易报错。
另外，我自己测试Android8，Android9，都是只能在start里看见包名，其他操作都不能做。
刷成6，才成功的。

**Comment by lyxhh** [comment]
用 Android 6，
